spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/terangafun?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate: 
      ddl-auto: update
#Hikari conf
spring:
  datasource: 
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      idle-timeout: 60000
      minimum-idle: 2
      leak-detection-threshold: 60000
#logging.level.root=TRACE
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        transaction: DEBUG
      hibernate:
        type: TRACE